<?php

namespace Database\Seeders;

use App\Models\FeedText;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        foreach(self::STATIC_TEXTS as $type => $texts) {
            foreach ($texts as $text) {
                FeedText::withTrashed()->firstOrCreate(['type'=>$type,'text'=>$text]);
            }
        }
    }

    const STATIC_TEXTS = [
        'fun-fact' => [
        ],
        'dad-joke' => [ // archived source: https://web.archive.org/web/20220615182248/https://www.countryliving.com/life/a27452412/best-dad-jokes/
            "I'm afraid for the calendar. Its days are numbered.",
            "My wife said I should do lunges to stay in shape. That would be a big step forward.",
            "Why do fathers take an extra pair of socks when they go golfing? In case they get a hole in one!",
            "Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.",
            "What do a tick and the Eiffel Tower have in common? They're both Paris sites.",
            "What do you call a fish wearing a bowtie? Sofishticated.",
            "How do you follow Will Smith in the snow? You follow the fresh prints.",
            "If April showers bring May flowers, what do May flowers bring? Pilgrims.",
            "I thought the dryer was shrinking my clothes. Turns out it was the refrigerator all along.",
            "What do you call a factory that makes okay products? A satisfactory",
            "Dear Math, grow up and solve your own problems",
            "What did the janitor say when he jumped out of the closet? Supplies! ",
            "Have you heard about the chocolate record player? It sounds pretty sweet",
            "What did the ocean say to the beach? Nothing, it just waved",
            "Why do seagulls fly over the ocean? Because if they flew over the bay, we'd call them bagels",
            "I only know 25 letters of the alphabet. I don't know y",
            "How does the moon cut his hair? Eclipse it",
            "What did one wall say to the other? I'll meet you at the corner",
            "What did the zero say to the eight? That belt looks good on you",
            "A skeleton walks into a bar and says, 'Hey, bartender. I'll have one beer and a mop.' ",
            "Where do fruits go on vacation? Pear-is! ",
            "I asked my dog what's two minus two. He said nothing",
            "What did Baby Corn say to Mama Corn? Where's Pop Corn? ",
            "What's the best thing about Switzerland? I don't know, but the flag is a big plus",
            "What does a sprinter eat before a race? Nothing, they fast! ",
            "Where do you learn to make a banana split? Sundae school",
            "What has more letters than the alphabet? The post office! ",
            "Dad, did you get a haircut? No, I got them all cut! ",
            "What do you call a poor Santa Claus? St. Nickel-less",
            "I got carded at a liquor store, and my Blockbuster card accidentally fell out. The cashier said never mind",
            "Where do boats go when they're sick? To the boat doc",
            "I don't trust those trees. They seem kind of shady",
            "My wife is really mad at the fact that I have no sense of direction. So I packed up my stuff and right! ",
            "How do you get a squirrel to like you? Act like a nut",
            "Why don't eggs tell jokes? They'd crack each other up",
            "I don't trust stairs. They're always up to something",
            "What do you call someone with no body and no nose? Nobody knows",
            "Did you hear the rumor about butter? Well, I'm not going to spread it! ",
            "Why couldn't the bicycle stand up by itself? It was two tired",
            "What did one hat say to the other? Stay here! I'm going on ahead",
            "Why did Billy get fired from the banana factory? He kept throwing away the bent ones",
            "Dad, can you put my shoes on? No, I don't think they'll fit me",
            "Why can't a nose be 12 inches long? Because then it would be a foot",
            "What does a lemon say when it answers the phone? Yellow! ",
            "This graveyard looks overcrowded. People must be dying to get in",
            "What kind of car does an egg drive? A yolkswagen",
            "Dad, can you put the cat out? I didn't know it was on fire",
            "How do you make 7 even? Take away the s",
            "How does a taco say grace? Lettuce pray",
            "What time did the man go to the dentist? Tooth hurt-y",
            "Why didn't the skeleton climb the mountain? It didn't have the guts",
            "What do you call it when a snowman throws a tantrum? A meltdown",
            "How many tickles does it take to make an octopus laugh? Ten tickles",
            "I have a joke about chemistry, but I don't think it will get a reaction",
            "What concert costs just 45 cents? 50 Cent featuring Nickelback! ",
            "What does a bee use to brush its hair? A honeycomb! ",
            "How do you make a tissue dance? You put a little boogie in it",
            "Why did the math book look so sad? Because of all of its problems! ",
            "What do you call cheese that isn't yours? Nacho cheese",
            "My dad told me a joke about boxing. I guess I missed the punch line",
            "What kind of shoes do ninjas wear? Sneakers! ",
            "How does a penguin build its house? Igloos it together",
            "I used to be addicted to soap, but I'm clean now",
            "A guy walks into a bar...and he was disqualified from the limbo contest",
            "You think swimming with sharks is expensive? Swimming with sharks cost me an arm and a leg",
            "When two vegans get in an argument, is it still called a beef? ",
            "I ordered a chicken and an egg from Amazon. I'll let you know..",
            "Do you wanna box for your leftovers? No, but I'll wrestle you for them",
            "That car looks nice but the muffler seems exhausted",
            "Shout out to my fingers. I can count on all of them",
            "If a child refuses to nap, are they guilty of resisting a rest? ",
            "What country's capital is growing the fastest? Ireland. Every day it's Dublin",
            "I once had a dream I was floating in an ocean of orange soda. It was more of a fanta sea",
            "Did you know corduroy pillows are in style? They're making headlines",
            "Did you hear about the kidnapping at school? It's okay, he woke up",
            "A cheeseburger walks into a bar. The bartender says, 'Sorry, we don't serve food here.' ",
            "I once got fired from a canned juice company. Apparently I couldn't concentrate",
            "I used to play piano by ear. Now I use my hands",
            "Have you ever tried to catch a fog? I tried yesterday but I mist",
            "I'm on a seafood diet. I see food and I eat it",
            "Why did the scarecrow win an award? Because he was outstanding in his field",
            "I made a pencil with two erasers. It was pointless",
            "How do you make a Kleenex dance? Put a little boogie in it! ",
            "I'm reading a book about anti-gravity. It's impossible to put down! ",
            "Did you hear about the guy who invented the knock-knock joke? He won the 'no-bell' prize",
            "I've got a great joke about construction, but I'm still working on it",
            "I used to hate facial hair...but then it grew on me",
            "I decided to sell my vacuum cleaner—it was just gathering dust! ",
            "I had a neck brace fitted years ago and I've never looked back since",
            "You know, people say they pick their nose, but I feel like I was just born with mine",
            "What's brown and sticky? A stick",
            "Why can't you hear a psychiatrist using the bathroom? Because the 'P' is silent",
            "What do you call an elephant that doesn't matter? An irrelephant",
            "What do you get from a pampered cow? Spoiled milk",
            "I like telling Dad jokes. Sometimes he laughs! ",
            "What's the best smelling insect? A deodor-ant",
            "I used to be a personal trainer. Then I gave my too weak notice",
            "Did I tell you the time I fell in love during a backflip? I was heels over head! ",
            "If a child refuses to sleep during nap time, are they guilty of resisting a rest? ",
            "I ordered a chicken and an egg online. I’ll let you know",
            "It takes guts to be an organ donor",
            "If you see a crime at an Apple Store, does that make you an iWitness? ",
            "I'm so good at sleeping, I can do it with my eyes closed! ",
            "I was going to tell a time-traveling joke, but you guys didn't like it",
            "What do you call a fake noodle? An impasta",
            "What do you call a belt made of watches? A waist of time",
            "What happens when a strawberry gets run over crossing the street? Traffic jam",
            "What do you call two monkeys that share an Amazon account? Prime mates",
            "What do you call a pony with a sore throat? A little hoarse",
            "Where do math teachers go on vacation? Times Square",
            "Whenever I try to eat healthy, a chocolate bar looks at me and Snickers",
            "What does garlic do when it gets hot? It takes its cloves off",
            "What's a robot's favorite snack? Computer chips",
            "How much does it cost Santa to park his sleigh? Nothing, it's on the house",
            "Mountains aren't just funny. They're hill areas",
            "What do clouds wear? Thunderwear.",
            "Why are piggy banks so wise? They're filled with common cents",
            "Why is Peter Pan always flying? He neverlands",
            "How do you get a good price on a sled? You have toboggan",
            "How can you tell if a tree is a dogwood tree? By its bark",
            "I used to hate facial hair, but then it grew on me",
            "It's inappropriate to make a 'dad joke' if you're not a dad. It's a faux pa",
            "What do you call a hot dog on wheels? Fast food! ",
            "Where do young trees go to learn? Elementree school",
            "Did you hear about the circus fire? It was in tents",
            "Can February March? No, but April May! ",
            "How do lawyers say goodbye? We'll be suing ya! ",
            "Wanna hear a joke about paper? Never mind—it's tearable",
            "What's the best way to watch a fly fishing tournament? Live stream",
            "Spring is here! I got so excited I wet my plants",
            "I could tell a joke about pizza, but it's a little cheesy",
            "Don't trust atoms. They make up everything! ",
            "When does a joke become a dad joke? When it becomes apparent",
            "I wouldn't buy anything with velcro. It's a total rip-off",
            "What’s an astronaut’s favorite part of a computer? The space bar",
            "I don't play soccer because I enjoy the sport. I'm just doing it for kicks! ",
            "Why are elevator jokes so classic and good? They work on many levels",
            "Why do bees have sticky hair? Because they use a honeycomb",
            "What do you call a fake noodle? An impasta",
            "Which state has the most streets? Rhode Island",
            "What did the coffee report to the police? A mugging",
            "What did the fish say when he hit the wall? Dam",
            "Is this pool safe for diving? It deep ends",
            "If you see a crime happen at the Apple store, what does it make you? An iWitness",
        ],
        'cat-fact' => [ // archived source: https://web.archive.org/web/20220718034242/https://cvillecatcare.com/veterinary-topics/101-amazing-cat-facts-fun-trivia-about-your-feline-friend/
            "A house cat’s genome is 95.6 percent tiger, and they share many behaviors with their jungle ancestors. These behaviors include scent marking by scratching, prey play, prey stalking, pouncing, chinning, and urine marking.",
            "Cats are believed to be the only mammals who don’t taste sweetness.",
            "Cats are nearsighted, but their peripheral vision and night vision are much better than that of humans.",
            "Cats are supposed to have 18 toes (five toes on each front paw; four toes on each back paw).",
            "Cats can jump up to six times their length.",
            "Cats’ claws all curve downward, which means that they can’t climb down trees head-first. Instead, they have to back down the trunk.",
            "Cats’ collarbones don’t connect to their other bones, as these bones are buried in their shoulder muscles.",
            "Cats have 230 bones, while humans only have 206.",
            "Cats have an extra organ that allows them to taste scents on the air, which is why your cat stares at you with her mouth open from time to time.",
            "Cats have whiskers on the backs of their front legs, as well.",
            "Cats have nearly twice the amount of neurons in their cerebral cortex as dogs.",
            "Cats have the largest eyes relative to their head size of any mammal.",
            "Cats make very little noise when they walk around. The thick, soft pads on their paws allow them to sneak up on their prey — or you!",
            "Cats’ rough tongues can lick a bone clean of any shred of meat.",
            "Cats use their long tails to balance themselves when they’re jumping or walking along narrow ledges.",
            "Cats use their whiskers to “feel” the world around them in an effort to determine which small spaces they can fit into. A cat’s whiskers are generally about the same width as its body. (This is why you should never, EVER cut their whiskers.)",
            "Cats walk like camels and giraffes: They move both of their right feet first, then move both of their left feet. No other animals walk this way.",
            "Male cats are more likely to be left-pawed, while female cats are more likely to be right-pawed.",
            "Though cats can notice the fast movements of their prey, it often seems to them that slow-moving objects are actually stagnant.",
            "Some cats are ambidextrous, but 40 percent are either left- or right-pawed.",
            "Some cats can swim.",
            "There are cats who have more than 18 toes. These extra-digit felines are referred to as being “polydactyl.”",
            "A cat’s average lifespan increased by a year over the span of time between 2002 and 2012, according to a study by Banfield Pet Hospital.",
            "According to The Huffington Post, cats typically sleep for 12 to 16 hours a day.",
            "Cats are crepuscular, which means that they’re most active at dawn and dusk.",
            "Cats are fastidious creatures about their “bathroom.” If you have more than one cat, you should have one litter box for each.",
            "Cats can spend up to a third of their waking hours grooming.",
            "Cats live longer when they stay indoors.",
            "Cats’ purring may be a self-soothing behavior, since they make this noise when they’re ill or distressed, as well as when they’re happy.",
            "Cats will refuse an unpalatable food to the point of starvation.",
            "Despite popular belief, many cats are actually lactose intolerant.",
            "Female cats have the ability to get pregnant when they are only 4 months old!",
            "Grapes and raisins, as well as onions, garlic, and chives, are all extremely harmful foods for cats. Grapes and raisins can cause kidney failure — although the reasoning behind that isn’t clear. Meanwhile, onions, garlic, and chives wreak havoc on your cat’s gastrointestinal system and can cause anemia.",
            "If you keep your cat active during the day, he will sleep better at night. If you’re not free-feeding your cat, you can also help her get a good night’s sleep by providing her with a substantial evening meal.",
            "It’s believed that catnip produces an effect similar to LSD or marijuana in cats. The effects of nepetalactone — the chemical in catnip that can makes cats crazy — wears off within 15 minutes, and won’t surface again for a few hours, even if your cat remains in sniffing distance.",
            "Kittens can be spayed or neutered when they are only eight weeks old. If possible, these procedures should be performed in the first 5 months of your cat’s life.",
            "Male cats who have been fixed need fewer calories to maintain their weight.",
            "Spaying and neutering can extend a cat’s life. The Banfield Pet Hospital study found that neutered males live an average of 62 percent longer than unneutered cats and spayed females live an average of 39 percent longer than unspayed cats.",
            "Your cat’s grooming process stimulates blood flow to his skin, regulates his body temperature and helps him relax.",
            "A cat with a question-mark-shaped tail is asking, “Want to play?”",
            "A slow blink is a “kitty kiss.” This movement shows contentment and trust.",
            "Cats have a unique “vocabulary” with their owner — each cat has a different set of vocalizations, purrs and behaviors.",
            "Cats have up to 100 different vocalizations — dogs only have 10.",
            "Cats find it threatening when you make direct eye contact with them.",
            "Cats mark you as their territory",
            "when they rub their faces and bodies against you, as they have scent glands in those areas.",
            "Cats may yawn as a way to end a confrontation with another animal. Think of it as their “talk to the hand” gesture.",
            "Hissing is defensive, not aggressive. “It’s an expression of fear, stress or discomfort of a threatened cat communicating ‘stay away,'",
            "If cats are fighting, the cat that’s hissing is the more vulnerable one.",
            "If your cat approaches you with a straight, almost vibrating tail, this means that she is extremely happy to see you.",
            "Kneading — which some people refer to as “making biscuits” — is a sign of contentment and happiness. Cats knead their mothers when they are nursing to stimulate the let-down of milk.",
            "Meowing is a behavior that cats developed exclusively to communicate with people.",
            "When a cat flops over and exposes his belly, it’s not always an invitation for a belly rub. A cat does this when he’s relaxed and showing trust.",
            "When cats hit you with retracted claws, they’re playing, not attacking.",
            "When dogs wag their tails, they may be expressing happiness. But this isn’t the case for cats! When your cat wags her tail, it’s her way of warning you that you are getting on her last nerve.",
            "When your cat sticks his butt in your face, he is doing so as a gesture of friendship.",
            "Whiskers are also good indicators of a cat’s mood. When a cat is scared, he put his whiskers back. But when a cat is in hunting mode, he puts his whiskers forward.",
            "Your cat drapes its tail over another cat, your dog, or you as a symbol of friendship.",
            "Cats are very fussy about their water bowls; some prefer to ignore their bowls entirely in favor of drinking from the sink faucet.",
            "Cats groom other cats — and sometimes people — in a ritual called allogrooming.",
            "Cats like to sleep on things that smell like their owners, such as their pillows and dirty laundry (ick!).",
            "Cats love to sleep in laundry baskets, too, because they’re basically hiding places with peep holes.",
            "Cats often attack your ankles when they’re bored.",
            "Certain cats go crazy for foods you wouldn’t expect, like olives, potato chips, and the hops in beer.",
            "For some reason, cats really dislike citrus scents.",
            "If you can’t find your cat, you should look in a box or a bag, as these are some of their favorite hiding spots!",
            "Male cats who try to get to a female in heat can show very bizarre behavior — for example, some have been known to slide down chimneys!",
            "Many cats like to lick their owner’s freshly washed hair.",
            "Some cats love the smell of chlorine.",
            "Thieving behavior is not uncommon among cats. They will often grab objects like stuffed animals, feather dusters, and other things that remind them of prey.",
            "A green cat was born in Denmark in 1995. Some people believe that high levels of copper in the water pipes nearby may have given his fur a verdigris effect.",
            "It turns out that Abraham Lincoln was a crazy cat president! He had four cats that lived in the White House with him.",
            "Maria Assunta left her cat, Tomasso, her entire $13 million fortune when she died in 2011.",
            "President Bill Clinton’s cat, Socks, was a media darling during the Clinton administration and was said to receive more letters than the President himself.",
            "Stubbs, a 17-year-old orange tabby, is mayor of the historic district of Talkeetna, Alaska.",
            "A cat’s learning style is about the same as a 2- to 3-year-old child.",
            "A cat’s purr vibrates at a frequency of 25 to 150 hertz, which is the same frequency at which muscles and bones repair themselves.",
            "A group of kittens is called a “kindle.”",
            "A house cat could beat superstar runner Usain Bolt in the 200 meter dash.",
            "About half of the cats in the world respond to the scent of catnip.",
            "Cat breeders are called “catteries.”",
            "Cats can be toilet-trained.",
            "Cats can drink sea water in order to survive. (In case you’re wondering, we can’t.)",
            "Cats don’t have an incest taboo, so they may choose to mate with their brothers and sisters.",
            "Cats dream, just like people do.",
            "Cats have contributed to the extinction of 33 different species.",
            "Cats perceive people as big, hairless cats.",
            "Cats were first brought to the Americas in colonial times to get rid of rodents.",
            "Collective nouns for adult cats include “clowder,” “clutter,” “glaring,” and “pounce.”",
            "Each cat’s nose print is unique, much like human fingerprints.",
            "Every Scottish Fold cat in the world can trace its heritage back to the first one, which was found in Scotland in the 1960s, says Cheryl Hogan, a Scottish Fold breeder and the committee chair for the breed at The International Cat Association (TICA).",
            "It’s not uncommon to see cats in food stores in big cities as a form of free — and adorable — pest control.",
            "Kittens in the same litter can have more than one father. This is because the female cat releases multiple eggs over the course of a few days when she is in heat.",
            "Male cats are the most sensitive to catnip, while kittens under 3 months old have no response at all.",
            "Most world languages have a similar word to describe the “meow” sound.",
            "People often think that they’ve stumbled over a purebred as a stray or in a shelter, but Hogan says that this is very uncommon. “Ninety-nine times out of 100 what you have found on the street will not be purebred anything,” she says. “Very seldom do breeders sell kittens that are not already spayed or neutered,” as purebred cats need to meet very strict standards.",
            "Some 700 million feral cats live in the United States, and many shelters run trap-neuter-release programs to stem the population growth.",
            "Studies suggest that domesticated cats first appeared around 3600 B.C.",
            "The first known cat video was recorded in 1894.",
            "There are about 88 million pet cats in the United States, which makes them the most popular pet in the country!",
            "Two hundred feral cats prowl the park at Disneyland, doing their part to control rodents — the ones who don’t wear funny outfits and speak in squeaky voices.",
            "White cats with blue eyes are prone to deafness."
        ],
    ];
}
